// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// appointmentDao is the data access object for the table appointment.
// You can define custom methods on it to extend its functionality as needed.
type appointmentDao struct {
	*internal.AppointmentDao
}

var (
	// Appointment is a globally accessible object for table appointment operations.
	Appointment = appointmentDao{internal.NewAppointmentDao()}
)

// Add your custom methods and functionality below.
