// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// favoriteDao is the data access object for the table favorite.
// You can define custom methods on it to extend its functionality as needed.
type favoriteDao struct {
	*internal.FavoriteDao
}

var (
	// Favorite is a globally accessible object for table favorite operations.
	Favorite = favoriteDao{internal.NewFavoriteDao()}
)

// Add your custom methods and functionality below.
