// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// houseFeatureDao is the data access object for the table house_feature.
// You can define custom methods on it to extend its functionality as needed.
type houseFeatureDao struct {
	*internal.HouseFeatureDao
}

var (
	// HouseFeature is a globally accessible object for table house_feature operations.
	HouseFeature = houseFeatureDao{internal.NewHouseFeatureDao()}
)

// Add your custom methods and functionality below.
