// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// houseDao is the data access object for the table house.
// You can define custom methods on it to extend its functionality as needed.
type houseDao struct {
	*internal.HouseDao
}

var (
	// House is a globally accessible object for table house operations.
	House = houseDao{internal.NewHouseDao()}
)

// Add your custom methods and functionality below.
