// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// recommendationDao is the data access object for the table recommendation.
// You can define custom methods on it to extend its functionality as needed.
type recommendationDao struct {
	*internal.RecommendationDao
}

var (
	// Recommendation is a globally accessible object for table recommendation operations.
	Recommendation = recommendationDao{internal.NewRecommendationDao()}
)

// Add your custom methods and functionality below.
