// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// userBehaviorDao is the data access object for the table user_behavior.
// You can define custom methods on it to extend its functionality as needed.
type userBehaviorDao struct {
	*internal.UserBehaviorDao
}

var (
	// UserBehavior is a globally accessible object for table user_behavior operations.
	UserBehavior = userBehaviorDao{internal.NewUserBehaviorDao()}
)

// Add your custom methods and functionality below.
