// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"SmartRental/internal/dao/internal"
)

// userPreferenceDao is the data access object for the table user_preference.
// You can define custom methods on it to extend its functionality as needed.
type userPreferenceDao struct {
	*internal.UserPreferenceDao
}

var (
	// UserPreference is a globally accessible object for table user_preference operations.
	UserPreference = userPreferenceDao{internal.NewUserPreferenceDao()}
)

// Add your custom methods and functionality below.
